name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH and deploy
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        ssh-keyscan ec2-13-60-55-55.eu-north-1.compute.amazonaws.com  >> ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-13-60-55-55.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
